### ISSUE TITLE
style.cssにanchorが生成されてないっぽい

### ISSUE THREAD

**Issue by TaharaKazuki** [magnun-github/mag-hp#1]
index.htmlで読み込んでるのがscssでbundleされたstyle.cssという認識なんですが  
style.cssにanchorに対して設定しているプロパティ値があたってないから、やりたい挙動（100px分headerを落とす）がうまくいってない感じです。

scssをトランスパイルしてる対応をvscodeの設定でやってると思うので  
そこのところを見直すのと
a.anchorのインデントを修正すると直るのでは？と思います。

```scss
a.anchor {
    display: block;
    padding-top: 100px;
    margin-top: -100px;
  } // <=インデントがおかしい
```

<img width="845" alt="スクリーンショット 2020-03-16 21 26 56" src="https://user-images.githubusercontent.com/15259879/76758378-edde9c80-67cc-11ea-8a80-16f31eb1d691.png">

devToolでか確認しても、aタグにanchorで指定してる値あたってないので
